# JS-DDPM Configuration: epsilon Prediction + Lp Norm (p=2.0)
# Joint-Synthesis DDPM for paired FLAIR/lesion mask generation
#
# ICIP 2026 Experiment: Lp norm ablation with epsilon prediction
# Part of ablation study: {epsilon, velocity, x0} × {p=1.5, p=2.0, p=2.5}


# =============================================================================
# Experiment Metadata
# =============================================================================
experiment:
  name: "epsilon_lp_2.0"
  output_dir: "./outputs/epsilon_lp_2.0"
  seed: 33

# =============================================================================
# Data Configuration (DATASET-AGNOSTIC)
# =============================================================================
data:
  # Path to pre-built slice cache (generated via jsddpm-cache command)
  cache_dir: "/media/mpascual/Sandisk2TB/research/jsddpm/data/epilepsy/slice_cache"

  # Data loader settings (dataset-agnostic)
  batch_size: 16
  num_workers: 0  # Set to 0 to avoid CUDA multiprocessing issues
  pin_memory: true

  transforms:
    target_spacing: [1.25, 1.25, 1.25]  # mm - resampled volume cropped to 160^3 via roi_size
    roi_size: [160, 160, 160]
    intensity_norm:
      type: "percentile"  # Options: "percentile", "minmax"
      lower: 0.5
      upper: 99.5
      b_min: -1.0
      b_max: 1.0
      clip: true

  # Needed for ConditionalEmbeddingWithSinusoidal
  slice_sampling:
    z_range: [34, 115]  # Valid z indices after resampling [min_z, max_z] (inclusive)
    filter_empty_brain: true
    brain_threshold: -0.9  # Threshold for considering pixel as brain in [-1,1] space
    brain_min_fraction: 0.05  # Minimum fraction of brain pixels to keep slice

  # Lesion oversampling strategy (dataset-agnostic)
  lesion_oversampling:
    enabled: true
    mode: "balance"  # "balance" for 50/50 lesion/non-lesion sampling
    weight: 3.0

# =============================================================================
# Conditioning Configuration
# =============================================================================
conditioning:
  z_bins: 30  # Number of bins for z-position quantization

  # Z-position encoding options
  use_sinusoidal: true
  max_z: 159  # Maximum z-index for sinusoidal encoding (0-indexed for 160 slices)

  # Classifier-free guidance (CFG)
  cfg:
    enabled: false
    null_token: 60
    dropout_prob: 0.1

# =============================================================================
# Model Configuration
# =============================================================================
model:
  type: "DiffusionModelUNet"
  spatial_dims: 2
  in_channels: 2   # [image, mask]
  out_channels: 2  # [image, mask]

  # Anatomical conditioning disabled for clean ablation
  anatomical_conditioning: false
  anatomical_conditioning_method: "concat"
  cross_attention_dim: 256

  anatomical_encoder:
    hidden_dims: [32, 64, 128]
    downsample_factor: 8
    positional_encoding: "sinusoidal"
    norm_num_groups: 8

  # UNet architecture
  channels: [64, 128, 256, 256]
  attention_levels: [false, false, true, true]
  num_res_blocks: 2
  num_head_channels: 32

  # Normalization
  norm_name: "GROUP"
  norm_num_groups: 32

  # Conditioning via class embeddings
  use_class_embedding: true

  # Dropout for regularization
  dropout: 0.0

  # Resblock updown
  resblock_updown: false

  # Cross-attention
  with_conditioning: false

# =============================================================================
# Diffusion Scheduler Configuration
# =============================================================================
scheduler:
  type: "DDPM"
  num_train_timesteps: 1000

  # Beta schedule
  schedule: "cosine"

  # Used for linear and scaled_linear schedules
  beta_start: 0.0015
  beta_end: 0.0195
  sig_range: 6.0

  # Prediction type
  prediction_type: "epsilon"
  # Clip sample during sampling
  clip_sample: true
  clip_sample_range: 1.0

# =============================================================================
# Sampler Configuration (for generation/visualization)
# =============================================================================
sampler:
  type: "DDIM"
  num_inference_steps: 300
  eta: 0.2

  # Classifier-free guidance scale
  guidance_scale: 1.0

# =============================================================================
# Training Configuration
# =============================================================================
training:
  # Batch size and workers
  batch_size: 16
  num_workers: 0
  pin_memory: true

  # Distributed training settings
  accelerator: "gpu"
  devices: 1
  strategy: "auto"

  # Self conditioning
  self_conditioning:
    enabled: true
    probability: 0.5

  # Optimizer
  optimizer:
    type: "AdamW"
    lr: 1.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.999]
    eps: 1.0e-8

  # Learning rate scheduler
  lr_scheduler:
    type: "CosineAnnealingLR"
    T_max: null  # Set to max_epochs if null
    eta_min: 1.0e-6

  # Training duration
  max_epochs: 500
  max_steps: null

  # Precision and gradient handling
  precision: "16-mixed"
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  accumulate_grad_batches: 1

  # Validation frequency
  val_check_interval: 1.0
  check_val_every_n_epoch: 1

  # Early stopping
  early_stopping:
    enabled: true
    monitor: "val/loss"
    patience: 25
    mode: "min"

  # Exponential Moving Average (EMA)
  ema:
    enabled: true
    decay: 0.999
    update_every: 1
    update_start_step: 0
    store_on_cpu: true
    use_buffers: true
    use_for_validation: true
    export_to_checkpoint: true

loss:
  # Pure Lp norm mode without FFL or uncertainty weighting
  mode: "mse_lp_norm"

  # Lp norm configuration
  lp_norm:
    p: 2.0

  # Uncertainty weighting - DISABLED
  uncertainty_weighting:
    enabled: false
    initial_log_vars: [0.0, 0.0]
    learnable: true
    clamp_range: [-5.0, 5.0]

  # Group uncertainty weighting - DISABLED
  group_uncertainty_weighting:
    enabled: false
    initial_log_vars: [0.0, 0.5]
    learnable: true
    clamp_range: [-5.0, 5.0]
    intra_group_weights: [1.0, 1.0, 1.0]

  # FFL - DISABLED
  ffl:
    enabled: false
    loss_weight: 1.0
    alpha: 1.35
    patch_factor: 2
    ave_spectrum: false
    log_matrix: true
    batch_matrix: false

  # Lesion pixel weighting (uniform for fair ablation)
  lesion_weighted_image:
    enabled: true
    lesion_weight: 1.0
    background_weight: 1.0

  lesion_weighted_mask:
    enabled: true
    lesion_weight: 1.0
    background_weight: 1.0

# =============================================================================
# Postprocessing Configuration
# =============================================================================
postprocessing:
  zbin_priors:
    enabled: true
    priors_filename: "zbin_priors_brain_roi.npz"
    prob_threshold: 0.20
    dilate_radius_px: 1
    gaussian_sigma_px: 0.7
    min_component_px: 500
    n_first_bins: 5
    max_components_for_first_bins: 3
    relaxed_threshold_factor: 0.1
    fallback: "prior"
    apply_to: ["validation", "visualization", "generation"]
    background_value: -1.0
    use_prior_directly: true

# =============================================================================
# Logging Configuration
# =============================================================================
logging:
  log_every_n_steps: 50

  logger:
    type: "wandb"
    wandb:
      project: "jsddpm-epilepsy"
      entity: "mario-pg02-icai-org"
      name: "epsilon_lp_2.0"
      tags: ["epilepsy", "diffusion", "jsddpm", "icip2026", "epsilon", "lp_norm", "p2.0"]
      notes: "ICIP2026 ablation: epsilon prediction + Lp norm (p=2.0)"
      offline: true

  # Checkpointing
  checkpointing:
    save_top_k: 1
    monitor: "val/loss"
    mode: "min"
    save_last: false
    every_n_epochs: 1
    filename: "jsddpm-{epoch:04d}-{val_loss:.4f}"

  # Callback Configuration
  callbacks:
    gradient_norm:
      enabled: true
      log_every_n_steps: 100

    snr:
      enabled: true
      log_every_n_epochs: 5
      n_samples: 100

    prediction_quality:
      enabled: true
      log_every_n_epochs: 5
      n_samples: 100
      timestep_bins: 10

# =============================================================================
# Visualization Configuration
# =============================================================================
visualization:
  enabled: true
  every_n_epochs: 1

  z_bins_to_show: null
  n_samples_per_condition: 1

  overlay:
    enabled: true
    alpha: 0.5
    color: [255, 0, 0]
    threshold: 0.3

  save_png: true
  save_npz: false

# =============================================================================
# Generation Configuration (for runners/generate.py)
# =============================================================================
generation:
  n_per_condition: 100
  z_bins: null
  classes: [0, 1]
  output_format: "npz"
  save_individual: true
  create_index_csv: true
