# =============================================================================
# JS-DDPM XAI Ablation C: High Eta (tests LF texture via sampling stochasticity)
# =============================================================================
#
# DIAGNOSTIC ANALYSIS (2026-01-25):
#   Baseline: x0_lp_1.5 (severity=0.185, AUC=0.996)
#   Secondary artifact: Texture smoothness (GLCM dissimilarity d=0.47, homogeneity d=-0.30)
#   Spectral concordance: -0.70 (classifier uses LF texture features)
#
# XAI ABLATION STUDY:
#   Proposal: Baseline + FFL(alpha=1.35) + self_cond 0.8 + eta 0.1
#   Ablation A: Proposal - FFL
#   Ablation B: Proposal - self_cond 0.8
#   >>> Ablation C: Proposal - eta 0.1  <--- THIS CONFIG
#
# WHAT THIS TESTS:
#   Does reduced stochasticity (eta=0.1) preserve LF texture?
#   - Spectral concordance=-0.70 shows the classifier detects LF texture patterns
#   - Higher eta (0.2) injects more stochastic noise during DDIM sampling, which
#     may corrupt the fine LF texture structure learned during training
#   - DDIM sigma = eta * sqrt((1-alpha_{t-1})/(1-alpha_t)) * sqrt(1-alpha_t/alpha_{t-1})
#   - eta=0.2 gives ~2x the noise injection of eta=0.1
#
#   Expected outcome: If severity worsens vs proposal, low eta is critical for LF quality
#
# CHANGES FROM PROPOSAL:
#   [REVERTED] sampler.eta: 0.1 -> 0.2 (back to baseline)
#   [KEPT] loss.mode: mse_lp_norm_ffl_groups (FFL active)
#   [KEPT] ffl: enabled with alpha=1.35, patch_factor=1, group_uncertainty [0.0, 1.0]
#   [KEPT] self_conditioning.probability: 0.8
#   [KEPT] devices: 2 (global batch 32)
#   [KEPT] lesion_weight: 3.0
#   [KEPT] ema.decay: 0.9995, dropout: 0.05, max_epochs: 1000, patience: 100


# =============================================================================
# Experiment Metadata
# =============================================================================
experiment:
  name: "xai_ablation_high_eta"
  output_dir: "./outputs/xai_ablation_high_eta"
  seed: 33

# =============================================================================
# Data Configuration
# =============================================================================
data:
  cache_dir: "/media/mpascual/Sandisk2TB/research/jsddpm/data/epilepsy/slice_cache"

  batch_size: 16
  num_workers: 0
  pin_memory: true

  transforms:
    target_spacing: [1.25, 1.25, 1.25]
    roi_size: [160, 160, 160]
    intensity_norm:
      type: "percentile"
      lower: 0.5
      upper: 99.5
      b_min: -1.0
      b_max: 1.0
      clip: true

  slice_sampling:
    z_range: [34, 115]
    filter_empty_brain: true
    brain_threshold: -0.9
    brain_min_fraction: 0.05

  lesion_oversampling:
    enabled: true
    mode: "balance"
    weight: 3.0

# =============================================================================
# Conditioning Configuration
# =============================================================================
conditioning:
  z_bins: 30
  use_sinusoidal: true
  max_z: 159

  cfg:
    enabled: false
    null_token: 60
    dropout_prob: 0.1

# =============================================================================
# Model Configuration
# =============================================================================
model:
  type: "DiffusionModelUNet"
  spatial_dims: 2
  in_channels: 2
  out_channels: 2

  anatomical_conditioning: false
  anatomical_conditioning_method: "concat"
  cross_attention_dim: 256

  anatomical_encoder:
    hidden_dims: [32, 64, 128]
    downsample_factor: 8
    positional_encoding: "sinusoidal"
    norm_num_groups: 8

  channels: [64, 128, 256, 256]
  attention_levels: [false, false, true, true]
  num_res_blocks: 2
  num_head_channels: 32

  norm_name: "GROUP"
  norm_num_groups: 32
  use_class_embedding: true

  dropout: 0.05

  resblock_updown: false
  with_conditioning: false

# =============================================================================
# Scheduler Configuration
# =============================================================================
scheduler:
  type: "DDPM"
  num_train_timesteps: 1000
  schedule: "cosine"
  beta_start: 0.0015
  beta_end: 0.0195
  sig_range: 6.0

  prediction_type: "sample"
  clip_sample: true
  clip_sample_range: 1.0

# =============================================================================
# Sampler Configuration
# =============================================================================
sampler:
  type: "DDIM"
  num_inference_steps: 500

  # [REVERTED] Back to baseline eta=0.2 (more stochastic sampling).
  # This tests whether near-deterministic sampling is needed for LF quality.
  eta: 0.2

  guidance_scale: 1.0

# =============================================================================
# Training Configuration
# =============================================================================
training:
  batch_size: 16
  num_workers: 0
  pin_memory: true

  accelerator: "gpu"
  devices: 2
  strategy: "ddp"

  # [KEPT] High self-conditioning (from proposal)
  self_conditioning:
    enabled: true
    probability: 0.8

  optimizer:
    type: "AdamW"
    lr: 1.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.999]
    eps: 1.0e-8

  lr_scheduler:
    type: "CosineAnnealingLR"
    T_max: null
    eta_min: 1.0e-6

  max_epochs: 1000
  max_steps: null

  precision: "16-mixed"
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  accumulate_grad_batches: 1

  val_check_interval: 1.0
  check_val_every_n_epoch: 1

  early_stopping:
    enabled: true
    monitor: "val/loss"
    patience: 100
    mode: "min"

  ema:
    enabled: true
    decay: 0.9995
    update_every: 1
    update_start_step: 0
    store_on_cpu: true
    use_buffers: true
    use_for_validation: true
    export_to_checkpoint: true

# =============================================================================
# Loss Configuration — KEPT: FFL active
# =============================================================================
loss:
  mode: "mse_lp_norm_ffl_groups"

  lp_norm:
    p: 1.5

  uncertainty_weighting:
    enabled: false
    initial_log_vars: [0.0, 0.0]
    learnable: true
    clamp_range: [-5.0, 5.0]

  # Group uncertainty weighting: same as proposal
  group_uncertainty_weighting:
    enabled: true
    initial_log_vars: [0.0, 1.0]  # Updated from [0.0, 1.5] for moderate FFL weight
    learnable: true
    clamp_range: [-5.0, 5.0]
    intra_group_weights: [1.0, 1.0, 1.0]

  # FFL parameters: same as proposal (alpha=1.35, patch_factor=1)
  ffl:
    enabled: true
    loss_weight: 1.0
    alpha: 1.35           # Updated from 1.0 for focal HF emphasis
    patch_factor: 1       # Updated from 2 for full frequency resolution
    ave_spectrum: false
    log_matrix: true
    batch_matrix: false

  lesion_weighted_image:
    enabled: true
    lesion_weight: 3.0
    background_weight: 1.0

  lesion_weighted_mask:
    enabled: true
    lesion_weight: 3.0
    background_weight: 1.0

# =============================================================================
# Postprocessing Configuration
# =============================================================================
postprocessing:
  zbin_priors:
    enabled: false
    priors_filename: "zbin_priors_brain_roi.npz"
    prob_threshold: 0.20
    dilate_radius_px: 1
    gaussian_sigma_px: 0.7
    min_component_px: 500
    n_first_bins: 5
    max_components_for_first_bins: 3
    relaxed_threshold_factor: 0.1
    fallback: "prior"
    apply_to: ["visualization"]
    background_value: -1.0
    use_prior_directly: true

# =============================================================================
# Logging Configuration
# =============================================================================
logging:
  log_every_n_steps: 50

  logger:
    type: "wandb"
    wandb:
      project: "jsddpm-epilepsy"
      entity: "mario-pg02-icai-org"
      name: "xai_ablation_high_eta"
      tags: ["epilepsy", "diffusion", "jsddpm", "xai_ablation", "x0", "ffl", "lp_1.5", "self_cond_0.8", "eta_0.2"]
      notes: "XAI ablation C: proposal with eta=0.2 (tests LF texture via sampling stochasticity)"
      offline: true

  checkpointing:
    save_top_k: 1
    monitor: "val/loss"
    mode: "min"
    save_last: false
    every_n_epochs: 1
    filename: "jsddpm-{epoch:04d}-{val_loss:.4f}"

  callbacks:
    gradient_norm:
      enabled: true
      log_every_n_steps: 100

    snr:
      enabled: true
      log_every_n_epochs: 5
      n_samples: 100

    prediction_quality:
      enabled: true
      log_every_n_epochs: 5
      n_samples: 100
      timestep_bins: 10

    # Texture quality tracking: wavelet HH + GLCM dissimilarity + LBP
    # Key metrics and targets:
    #   1. wavelet_hh_ratio: target >0.85 (baseline: 0.787)
    #   2. glcm_dissimilarity_ratio: target ~1.0 (baseline d=0.47)
    #   3. lbp_code8_ratio: target ~1.0
    # With higher eta (0.2), texture noise may degrade GLCM/LBP metrics
    texture_quality:
      enabled: true
      log_every_n_epochs: 25
      n_samples: 32
      lbp_radius: 1
      lbp_n_points: 8
      wavelet: "db4"
      compute_full_texture: false
      run_on_first_epoch: true
      fast_inference_steps: 50
      batch_size: 8

# =============================================================================
# Visualization Configuration
# =============================================================================
visualization:
  enabled: true
  every_n_epochs: 1

  z_bins_to_show: null
  n_samples_per_condition: 1

  overlay:
    enabled: true
    alpha: 0.5
    color: [255, 0, 0]
    threshold: 0.3

  save_png: true
  save_npz: false

# =============================================================================
# Generation Configuration
# =============================================================================
generation:
  n_per_condition: 100
  z_bins: null
  classes: [0, 1]
  output_format: "npz"
  save_individual: true
  create_index_csv: true
